### ISSUE TITLE
能支持MAC键盘吗?

### ISSUE THREAD

**Issue by waterfish007** [Lotlab/lkb-configurator#1]
你好！
觉得这个方案非常好，我想基于平台基本上做87的一套键盘，基本就是keychron　k1的样子吧。市面唯一一款完全支持MAC的键盘，但是没有标准轴。但是我研究了一圈，能找到mac的keycode，但是tmk和qmk都没有针对mac的对应码表。不知道你们能补充上去吗？硬件设计方便我觉得不是问题，固件这里就卡住我了。
Mac/iOS的支持目前在机械键盘上来讲，基本是空白的。

**Comment by waterfish007** [comment]
甚至很适合很方便做成标准的模块，完全兼容替换K375S。

**Comment by jim-kirisame** [comment]
你走错地方了，固件问题去隔壁nrf52-keyboard.

而且mac和ios支持本来就有，只不过按键名称和windows上略有不同而已。
