### ISSUE TITLE
当在非当前目录下运行 server 时，会找不到前端文件

### ISSUE THREAD

**Issue by alexazhou** [Lotlab/lkb-configurator#11]
当启动非当前目录下的 server 时，会无法访问前端，我开始以为是无离线使用功能，提了个 issue，后来发现弄错了（https://github.com/Lotlab/lkb-configurator/issues/10），应该是少了个 chdir 

<img width="724" alt="截屏2022-01-16 下午4 19 57" src="https://user-images.githubusercontent.com/9353779/149652569-4819a48a-8aae-4967-aa4b-284edab6ff24.png">

**Comment by jim-kirisame** [comment]
以后修，现在请先cd到目标目录运行。

**Comment by jim-kirisame** [comment]
修复起来比较麻烦所以就不修了，现在在非当前目录下运行会有提示。
