### ISSUE TITLE
mac版本配置软件无法识别到键盘且配置工具没有响应

### ISSUE THREAD

**Issue by syz0610** [Lotlab/lkb-configurator#12]
## 概况
- 系统环境：macOS Monterey 12.1 MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
- 键盘类型：Glab Omega84
- 浏览器版本：Safari 版本15.2 (17612.3.6.1.6) 以及 Google Chrome 版本 100.0.4896.127（正式版本） (x86_64)
- 配置程序版本：lkb-configurator-osx-x64-2021-11-13_1.0.3.0-0-g86cdcae.tar.gz

## 具体现象
- USB Type-C 线连接一头为键盘，一头到笔记本雷电口，此时通过macOS键盘配置可以发现Lotlab设备且设置；
- 设置成功后有线模式不可用，敲击键盘无输出；
- 切换到蓝牙模式可用；
- 按照配置程序的Readme说明操作后打开配置页面显示配置工具没有响应且无法识别到键盘，具体现象如下图：
![image](https://user-images.githubusercontent.com/10899270/167061537-5ac28a6e-0d4c-498d-a317-67fb16298d17.png)
![image](https://user-images.githubusercontent.com/10899270/167061558-f51ea538-0706-4da5-99cc-7db882281c05.png)
![image](https://user-images.githubusercontent.com/10899270/167061589-8e63a4fa-899d-48d6-bb52-f429cb96193f.png)

**Comment by syz0610** [comment]
补充：之前是在Windows 10 专业工作站 版本20H1上配置成功并切换到mac上使用的，目前为止蓝牙模式没问题。

**Comment by jim-kirisame** [comment]
请先参考readme确认相关权限是否已授予

**Comment by syz0610** [comment]
确认给过可执行权限了,保险起见我给了777权限外加sudo运行，还是不行

**Comment by jim-kirisame** [comment]
mac有自己的权限管理，请先确认readme中的权限是否授予
