### ISSUE TITLE
希望得到解答

### ISSUE THREAD

**Issue by kaluochan** [Lotlab/lkb-configurator#13]
关于lotlab键盘配置工具上面，会有设置键盘关机项，但设置关机操作后，好像没有开机的按钮了？这样的情况下，怎么操作开机？这个模式和睡眠功能有什么不一样吗？

因为我在用45配列键盘考虑到外带防误触，这两个功能我来说会有实用性。

**Comment by jim-kirisame** [comment]
“关机”按钮并不是官方固件的功能，关于此功能的问题请咨询你的键盘厂商。
