### ISSUE TITLE
GT Planck Rev.A 滑鼠功能可以取消或調節游標的加速和延時嗎

### ISSUE THREAD

**Issue by claudiohk** [Lotlab/lkb-configurator#15]
如題。

我的鍵盤資訊如下﹕

    制造商: [Glab](https://glab.online/)
    产品名称：GT Planck
    硬件版本：Rev.A
    硬件序列号：ACDD9E59
    固件版本：1178C72E

**Comment by jim-kirisame** [comment]
您好，通过配置工具是无法修改模拟鼠标的加速度配置的。您可能需要联系您的设备生产商，获取固件源码并修改固件才能达到您想要的效果。
