### ISSUE TITLE
cannot launch the latest version at macos version 14.3.1 64bit 

### ISSUE THREAD

**Issue by iristhc** [Lotlab/lkb-configurator#17]
success in launching v1.0.5.0 but failure in launching v1.0.6.1
<img width="571" alt="Screenshot 2024-10-18 at 8 59 12 PM" src="https://github.com/user-attachments/assets/37d26437-82d6-4033-93af-84078a5f3939">

**Comment by jim-kirisame** [comment]
which device are you using? We change the package arch for macos from x86 to arm64 since v1.0.6.0

**Comment by iristhc** [comment]
here is my device, I am not familiar with computer stuff so I am not sure
<img width="245" alt="Screenshot 2024-10-18 at 9 16 51 PM" src="https://github.com/user-attachments/assets/57735b22-bc9b-4de4-bf55-6e4745b8bab6">
It is a apple M1 so I think it is supports ARM64?

**Comment by jim-kirisame** [comment]
sure, Apple M1 is arm64 device. Could you remove semi-colon and exit after the command line and try again? Or `cd` to the directory first then run the executable.

**Comment by iristhc** [comment]
i tried both methods but still cannot launch it :(

<img width="830" alt="Screenshot 2024-10-18 at 9 47 54 PM" src="https://github.com/user-attachments/assets/de34c81c-a45b-4f95-ad38-9b858567cc17">

**Comment by HotThoughts** [comment]
I encountered the same issue when using v1.0.6.1. Any idea what should we do?


Chip: Apple M1 Pro
MacOS: 15.1.1 (24B91)


```
❯ ./lkb-configurator-server 
zsh: killed     ./lkb-configurator-server
```

**Comment by jim-kirisame** [comment]
> I encountered the same issue when using v1.0.6.1. Any idea what should we do?
> 
> Chip: Apple M1 Pro MacOS: 15.1.1 (24B91)
> 
> ```
> ❯ ./lkb-configurator-server 
> zsh: killed     ./lkb-configurator-server
> ```

I have no idea about this problem, could you try to use the universal version with dotnet sdk just like what you do in v1.0.5.0?

----

Edit:

Is there any strange log in your system log? You may [check your system log in console.app](https://support.apple.com/en-hk/guide/console/cnsl1012/mac)

**Comment by HotThoughts** [comment]
Hello, thanks for your reply. The universal version works in my MacBook. I installed .NET Runtime 8.0.11.

**Comment by ZhaoJunnNie** [comment]
The same problem, and the the console.app shows
```
ASP: Security policy would not allow process: 71771
```

**Comment by jim-kirisame** [comment]
> The same problem, and the the console.app shows
> 
> ```
> ASP: Security policy would not allow process: 71771
> ```

Hi, I have upload the version 1.0.7.0 just now, which add code signature to fix the problem. Could you try it and give me some feedback?

**Comment by ZhaoJunnNie** [comment]
> > The same problem, and the the console.app shows
> 
> > 
> 
> > ```
> 
> > ASP: Security policy would not allow process: 71771
> 
> > ```
> 
> 
> 
> Hi, I have upload the version 1.0.7.0 just now, which add code signature to fix the problem. Could you try it and give me some feedback?

I can comfirm this has been fixed by this release, Thanks

**Comment by jim-kirisame** [comment]
> > > The same problem, and the the console.app shows
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > ASP: Security policy would not allow process: 71771
> > 
> > 
> > > 
> > 
> > 
> > Hi, I have upload the version 1.0.7.0 just now, which add code signature to fix the problem. Could you try it and give me some feedback?
> 
> I can comfirm this has been fixed by this release, Thanks

Thank you and all other people in this thread, I will close this issue since it's fixed.
