### ISSUE TITLE
No actual release for recent versions

### ISSUE THREAD

**Issue by lightingghost** [Lotlab/lkb-configurator#2]
It seems there is no actual configurator released for several recent versions, for example 0.9.9.10. Outside mainland China, baidu yun is slow and often breaks. I am not able to download anything from baidu yun.

**Comment by jim-kirisame** [comment]
I'm very sorry for this. It's hard for me to upload file to github on the past few month, so I only provide BaiduYun disk. Now I have upload them to github, so you can download it now.
