### ISSUE TITLE
online keyboard builder does not support specific key functions

### ISSUE THREAD

**Issue by lightingghost** [Lotlab/lkb-configurator#4]
I am trying to use https://keyboard.lotlab.org/ to configure my keyboard. However, I could not find some key functions which exists in lotkb builder, for example TRICKY_ESC, PRINT_BAT, etc.

**Comment by jim-kirisame** [comment]
lkb builder is not maintain by me and the code of that firmware is not on my branch. So it's reasonable that the configurator does not support those function which is not support in the firmware of my branch.
