### ISSUE TITLE
不支持GT BLE60 rev.F

### ISSUE THREAD

**Issue by nancheung** [Lotlab/lkb-configurator#6]
1. **键盘选择** 没有GT BLE60 rev.F选项
2. **附加说明** 插入GT BLE60 rev.**F**设备识别为GT BLE60 rev.**E**
3. **保存键位后，键位混乱**
    CapsLock变为s，a变为d，s变为f，后面的键依次变换，
    只要点击了“应用”即可复现，载入默认设置也是如此。
    > **非常严重，GT BLE60 rev.F目前无法编辑键位！！！**

**Comment by jim-kirisame** [comment]
fixed.
